// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6xwIqeWpvjOTFhK3tY0t2b4CCj4ag7gE',
    appId: '1:609100779598:web:2319df96d0ddfd406ab31f',
    messagingSenderId: '609100779598',
    projectId: 'gestiontache-16d02',
    authDomain: 'gestiontache-16d02.firebaseapp.com',
    storageBucket: 'gestiontache-16d02.appspot.com',
    measurementId: 'G-2P024L94VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0CmBOAi8AmgADs6HZnPQZNuomn_VDSM',
    appId: '1:609100779598:android:b4202fd06975162c6ab31f',
    messagingSenderId: '609100779598',
    projectId: 'gestiontache-16d02',
    storageBucket: 'gestiontache-16d02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoRl9zsqei-qO0avd0YFQ3jPwOlvpapU',
    appId: '1:609100779598:ios:0628097c9e102fcd6ab31f',
    messagingSenderId: '609100779598',
    projectId: 'gestiontache-16d02',
    storageBucket: 'gestiontache-16d02.appspot.com',
    iosBundleId: 'com.example.gestionTache',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoRl9zsqei-qO0avd0YFQ3jPwOlvpapU',
    appId: '1:609100779598:ios:0628097c9e102fcd6ab31f',
    messagingSenderId: '609100779598',
    projectId: 'gestiontache-16d02',
    storageBucket: 'gestiontache-16d02.appspot.com',
    iosBundleId: 'com.example.gestionTache',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6xwIqeWpvjOTFhK3tY0t2b4CCj4ag7gE',
    appId: '1:609100779598:web:6c581716156e92796ab31f',
    messagingSenderId: '609100779598',
    projectId: 'gestiontache-16d02',
    authDomain: 'gestiontache-16d02.firebaseapp.com',
    storageBucket: 'gestiontache-16d02.appspot.com',
    measurementId: 'G-3Y4QSK5KBW',
  );
}
